name: Build

on:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: windows-latest
    env:
      QT_VERSION: 6.8.3
      QT_VSTOOLS_VERSION: 3.3.1

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          vs-version: 17
          msbuild-architecture: x64

      - name: Add QtMSBuild
        shell: pwsh
        run: |
          $ProgressPreference = 'SilentlyContinue'
          Invoke-WebRequest https://download.qt.io/official_releases/vsaddin/${Env:QT_VSTOOLS_VERSION}/qt-vsaddin-msbuild-${Env:QT_VSTOOLS_VERSION}.zip `
                            -OutFile vstools-msbuild.zip
          Expand-Archive -Path .\vstools-msbuild.zip -DestinationPath .\MsBuild -Force

      - name: Setup Qt
        uses: jurplel/install-qt-action@v4.1.1
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: win64_msvc2022_64
          modules: 'qtactiveqt qthttpserver qtwebsockets'

      - name: NuGet restore
        shell: pwsh
        run: |
          nuget restore src\HomeAssistantDesktop.sln

      - name: Build
        shell: pwsh
        env:
          QTMSBUILD: ${{ github.workspace }}\MsBuild
        run: |
          msbuild src\HomeAssistantDesktop.sln /p:Configuration=Release /p:Platform=x64 /p:QtInstall=$Env:QT_ROOT_DIR

      - name: Add binary dependencies
        shell: pwsh
        run: |
          cd bin\x64\Release
          windeployqt --release --no-translations --no-system-d3d-compiler --no-system-dxc-compiler --no-compiler-runtime .\HomeAssistantDesktop.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: HomeAssistantDesktop
          path: bin\x64\Release
          retention-days: 10
